version: '3.8'

services:
  db:
    image: postgres:16
    container_name: pg-strenghth
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
